name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.1

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install
        run: yarn

      - name: check types
        run: yarn tsc -p . --noEmit

      - name: check style
        run: yarn style --check

      - name: build
        run: yarn build

      - name: Upload zipped distributables
        uses: actions/upload-artifact@v2.2.3
        with:
          # Artifact name
          name: Distributables
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            chrome.zip
            firefox.zip
            src.zip
          if-no-files-found: error
