name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2.3.1

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}      

      - name: install build tools
        run: brew install imagemagick

      - name: install
        run: yarn

      - name: check types
        run: yarn tsc -p . --noEmit

      - name: check style
        run: yarn style --check

      - name: build
        run: yarn build

      - name: Zip
        uses: TheDoctor0/zip-release@0.4.1
        with:
          # Filename for archive
          filename: accessibyebye.zip
          # Working directory before zipping
          directory: dist
          
      - name: Release
        uses: ncipollo/release-action@v1.8.1
        with:
          # Artifact name
          artifacts: accessibyebye.zip
          # Release name
          name: AccessiByeBye
          # Branch
          commit: master
          # secrets.GITHUB_TOKEN
          token: ${{ secrets.GITHUB_TOKEN }}
